// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import MoneyInputController from "./money_input_controller.js"
application.register("money-input", MoneyInputController)

import PriceHistoryChartController from "./price_history_chart_controller.js"
application.register("price-history-chart", PriceHistoryChartController)

import SortSelectController from "./sort_select_controller.js"
application.register("sort-select", SortSelectController)
